### PR TITLE
Change Wirm cert to 10 year expiry

### PR DESCRIPTION
**Pull request by tophercullen**
WinRM stops working if the certificate expires. Given this it is undesirable to lose remote access, a longer certificate would be desirable. However, the New-SelfSignedCertificate on 2012 r2 only does one year certificates.  I don't know of any 'easy' way for doing this, so here's spaghetti code.

### CODE REVIEW

**Comment by tophercullen** [comment]
I can rebase this pull requests. I still think its needed. Losing access after a year is pretty bad.

**Comment by NimishaS** [comment]
@tophercullen , please rebase the PR.

**Comment by NimishaS** [comment]
@tophercullen , please rebase the PR. Also, please share the URL for your repository. We are not able to clone or add your repository with name `unknown repository`.

**Comment by tophercullen** [comment]
@NimishaS This PR is foobar, I'm closing it and opening a new one that will actually work.

**Pull request closed without merging**
