### PR TITLE
New Feature: Allow re-use of existing ENI for primary interface

### PR DESCRIPTION
**Pull request by datascope**
I need to be able to re-use an available ENI by attaching it as the primary interface. This change allows me to do so.

### CODE REVIEW

**Comment by datascope** [comment]
Sorry if I have missed the protocol. Please let me know whether this fits in with the 'big picture'.

**Comment by SrikarshVardhanreddyKolanu** [comment]
Can admins please merge this pull request as it is very useful for launching a new instance with existing interface to get the old ip.

**Comment by dheerajd-msys** [comment]
@datascope, Thanks for your contribution. I've verified this and it is working properly. We will merge it after resolving conflicts.

**Comment by dheerajd-msys** [comment]
@datascope, We cherry picked your commits and resolved conflicts.  Verified the changes successfully.
We will be merging it through https://github.com/chef/knife-ec2/pull/515.

Thanks for your contribution.

**Comment by datascope** [comment]
Thanks for your help, I've been waiting quite a while for this.

**Comment by btm** [comment]
Merged in https://github.com/chef/knife-ec2/pull/515, will be in an upcoming knife-ec2 release.

**Pull request closed without merging**
