### PR TITLE
Allow option to use default vpc mode to allow a vpc EIP without subnet-id

### PR DESCRIPTION
**Pull request by tim95030**
This allows usage of EIPs on the default vpc

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by btm** [comment]
We should be able to detect if we're on VPC rather than require yet another flag for success on VPC.

https://github.com/chef/knife-ec2/issues/380

**Comment by tim95030** [comment]
I have had this as a patch on our internal version because our default deployments use the default VPC which doesn't work with the current code. I am definitely fine with not using a flag. I haven't worked on this in a long time just finally made the pull request so I would hopefully not have to keep applying this patch every time I want to upgrade.

**Comment by tas50** [comment]
I'm going to close this out at this point since there's merge conflicts and it would require a rebase / DCO sign off before we could move forward.

**Pull request closed without merging**
