### PR TITLE
Please also read aws_session_token from credentials file

### PR DESCRIPTION
**Pull request by datascope**
The AWS session token from is supported as a knife option but overlooked when read from the aws credentials file. This one line update to ec2_base.rb fixes that for me. Hopefully, it helps others too.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @datascope

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by datascope** [comment]
Also please go ahead and delete the file 'test' when merging. It was an oversight.

**Comment by Vasu1105** [comment]
@datascope  - Could you please delete the file test and push the code.

**Comment by NimishaS** [comment]
@datascope please rebase the code too.

**Comment by datascope** [comment]
Sure I'll fix it shortly.

**Comment by datascope** [comment]
That looks good to me. Let me know if you need anything else.

**Comment by gbish** [comment]
Hi,

I've just read an article and I have some questions that you may really  know the answer, please read it here <http://stoltopovu.fortheloveofthebean.com/oinzisr>

Be well, hebgb@blueyonder.co.uk

**Comment by gbish** [comment]
Hey,

Just look at that great stuff outta here! You're gonna love it, I swear! More info here <http://jostotreva.rsvpetc.com/oiaoi>

Later, hebgb@blueyonder.co.uk

**Comment by gbish** [comment]
Hey,

I've found a very easy tutorial on the stuff we were talking about, look here <http://nofraliwe.1474investments.com/oingovyk>

Best Wishes, hebgb@blueyonder.co.uk

**Pull request merged**
