### PR TITLE
Pointing docs at itself.  This is better then the non-existant chef.io docs.

### PR DESCRIPTION
**Pull request by zmalone**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by zmalone** [comment]
I've signed the ICLA before, the the Supermarket marks me as having already signed it.  I think the pull request bot might have a problem.

**Comment by juliandunn** [comment]
It's because the e-mail address has to match what's in Supermarket. Anyway, this is a trivial fix that doesn't require a CLA so I'll just merge it.

**Comment by gbish** [comment]
Hi,

I've visited a wonderful place recently, it amazed me! Just take a look here <http://ntyvelyphu.americanveteransupport.com/oiyexic>

Take care, hebgb@blueyonder.co.uk

**Pull request merged**
