### PR TITLE
Fix the badges and other URLs in the readme

### PR DESCRIPTION
**Pull request by tas50**
opscode -> chef change in github broke things.

### CODE REVIEW

**Comment by tas50** [comment]
Any chance we can get this merged?  It seems pretty obvious to fix the links and badges.

**Comment by NimishaS** [comment]
@tas50 , PR looks good. Can you please rebase this with master?

**Comment by tas50** [comment]
@NimishaS This is ready to go now.

**Comment by NimishaS** [comment]
Thanks @tas50

**Pull request merged**
