### PR TITLE
Avoid sending nil runlist to Chef::Knife::Boostrap

### PR DESCRIPTION
**Pull request by btm**
Also fixes chef/chef#4131, see also chef/chef#4149

I manually tested this and it worked (testing mixlib-cli is still nigh impossible?)

### CODE REVIEW

**Comment by btm** [comment]
@danielsdeleo

**Comment by danielsdeleo** [comment]
:+1:

**Comment by chefsalim** [comment]
:+1:

**Comment by ksubrama** [comment]
:+1:

**Comment by mwrock** [comment]
:+1:

**Comment by gbish** [comment]
Hi, I found some new stuff for you, i think you're gonna like it, more info at <http://thashepryba.luvandmoney.net/oikbjjui>

hebgb@blueyonder.co.uk

**Pull request merged**
