### PR TITLE
Working on command line option changes as per chef 12

### PR DESCRIPTION
**Pull request by Vasu1105**

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## Non-GitHub Verified Committers

There are 1 commit author(s) whose commits are authored by a non-GitHub verified email address. Chef will have to manually verify that they are authorized to contribute.

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by Vasu1105** [comment]
Will be creating another

**Comment by gbish** [comment]
Hi,

There are so many cool things that you have see! I was really surprised, just take a look <http://styspaphugi.gabrielsong.com/oimiwbwm>

hebgb@blueyonder.co.uk

**Comment by gbish** [comment]
Hey,

Look at that! Wooow! It's so amazing and interesting, and even sometimes shocking! Just take a look here <http://sytejunte.clearmar.com/oilddqy>

hebgb@blueyonder.co.uk

**Pull request closed without merging**
