### PR TITLE
Remove -s option for data bag secret because it conflicts with -s for subnets...

### PR DESCRIPTION
**Pull request by eherot**
...which was there first.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
:+1:

**Comment by NimishaS** [comment]
@eherot , we are using your input. We are also removing -s option of subnet as knife already has this option for server-url.
Here is the PR: https://github.com/chef/knife-ec2/pull/273

**Comment by eherot** [comment]
Ah right I totally forgot about that one. S is a popular letter of the alphabet. Thanks for following up!

**Comment by NimishaS** [comment]
@eherot, PR https://github.com/chef/knife-ec2/pull/273 has been merged with your changes in it. Closing this PR. Thank you for your help!

**Pull request closed without merging**
