### PR TITLE
[MSYS-693]check  travis failure

### PR DESCRIPTION
**Pull request by harikesh-kolekar**
Signed-off-by: MSys <harikesh.kolekar@msystechnologies.com>

### CODE REVIEW

**Comment by btm** [comment]
What's actually failing here? Is there a card for this failure? Could this mean that this version knife-ec2 won't work with the latest version of Chef 12?

**Comment by piyushawasthi** [comment]
The safe navigation support `&` added in ruby 2.3.0 that why travis is failing for https://github.com/chef/chef/blob/master/lib/chef/util/dsc/lcm_output_parser.rb#L88. If chef is not supporting ruby version less than 2.3.0. So here we can modify ruby version `- 2.2.7` to `2.3.0` in travis.yml https://github.com/chef/knife-ec2/blob/master/.travis.yml#L14

**Comment by harikesh-kolekar** [comment]
@btm For chef 12.20.21 need ruby 2.3 so travis get failed for ruby 2.2.7 build https://travis-ci.org/chef/knife-ec2/builds/292023904?utm_source=github_status&utm_medium=notification

**Comment by harikesh-kolekar** [comment]
@piyushawasthi  If any user uses chef 12 with ruby 2.2 and if he wants to install knife-ec2 then its get failed,
the user have to upgrade chef-dk with the latest version and then he can able to install knife-ec2 gem

**Comment by NimishaS** [comment]
@btm, there are 2 options to fix this issue now. Either remove `rvm 2.2.7` from Travis or the changes made in this PR.
Removing rvm 2.2.7 will mean that `knife-ec2` will not work with any Chef 12. @harry's solution will make it work with all Chef 12s except `12.21.20`.

**Comment by btm** [comment]
@NimishaS so does this work with Chef 12.21.26 which was released on 10/27? If so, can we drop that pin and it'll just never use that one version? 

From what I'm gathering this was fixed in Chef 12 by https://github.com/chef/chef/commit/105bc48349973ab966aa82d25262434030e13ed7, which is included in Chef 12.21.26. So we're fine now without this change, yes?

**Comment by btm** [comment]
Yup, I re-ran the job on https://github.com/chef/knife-ec2/pull/510 and it is green now.

**Pull request closed without merging**
